robot:

  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.5
  kinematics_solver_search_resolution: 0.5
  solve_type: Distance
  position_only_ik: True


